appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: tws9566t9qUWvGlyX7gneM5TLDdZCa+UNGJarnrJZ6xm604xvWOe6XQfl1C+gy3zr2z59rvtYmrJqBu88QBk2gZ2V/44fuQ+aDo2oJ+O39pcig6YhIWS9b2qOmWEMc8ep/Zl9Q6sYyBvEMwDZ057qlNvYmEudUtdrhnIaR2E2FqMVh0Zc/EM/eI6KLISrcaxmfrqElp5DEcPA+aLQH6j6oy0opHLcB0QpF+qQlVlrAVF/NiITCx28GNk+kENgL3G6gVei/1K+ionCgj9joaYLj8gFkaQ1M2P1wMakIbqtgw4UJjE5o88lqdSWvxnerlMV1w6IK7CnLWVEBCYqGi+rLzTuczdWK5NoNTAgwnXLyOM5uMuUQUyLdLbsLu59PxA5Pouj1H/RowAglnZ1msFd9KMTTvSc/2tLzLYgKEU/B6PzBdLRr9+1SHrBd1lB1G1Ofp60fKFEa0zWe+ftWCaJF83YCBQ4FtU8hwNevtuDydneFKfu4KlK0c8iGrKjvrw4temov28YQkMfnkROFpqijUKYn21BrfPnmjDC8eoryRxCljHC8DsNFa6OxxzikQeWAc/ChbmrOPKzhAY89yisEGld1vsU8a1R1U0sHo4RnWYYh0avYerUuUjI2W17YBuV3IU10x/cDGXzBn9WzInpJi0BEEy7JRAQT1VUv7hlgY=}
conda_forge_output_validation: true
