travis:
  secure:
    BINSTAR_TOKEN: rThwnSdoe2FDzp/XwkYszNGGvLL0dUrp8qvisO6PckbUZsjTao+ON92yET+edPUMID/ciLCXMKCPgLLBvoUT+etxJ9IyUBiZDbMU1aHoS4eSftwLgdU9YYtElxdnzIZgORmEs1V2UeBZ2tMkGeODREfFa5YxXeLfGq9v/5K00gvZHHaTHKbFxaBAZBPKkYWuWt5fbeo/VJKsaW8i43OeaJL0bFxsPFFIMPca4WQbCATAEF7ABlmTERUOo81HeFXsaGA/8h+03n11i4Gr4GbWqEovKSWdVfeuSt5XbBmXOBImrJGMtoh83ByxpGrMoO78gbZG19ZcmkORP4jQPDt9DhuCBow1eHSoh/qTWgKfAdb0eGl6U9AOAPStMZWN6Ygk+LWGyVTmK6Wz1vFbPcXjz7vlJX6BfoBK5j7yQ019Acq1ujl//3A/AZsuzCB668OJzWJmmOFwJpsDGYpRqkvZpFBd/GmqTwYFik8E4ZDOkrlCbb8+yv+js97INHQCpByv2/J8qk8VD3u3YWmROBujS0C7baa5vV9qrJUrt72A28wysDzuyye9MSCbU3VNlWdriXzrx7FgmZNoq01Z3ohFGevHOmK99VEeiZ6wuMdiCedPRLY3F3sP3aV9FZOnSRlMZC1W43AKINXAnSJ/FOnUYOtzf5lOkA0/A4V4IvXmLPk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
